version: '2'
services:
  atlassian-confluence-build:
    image: maven:3-jdk-8-alpine
    volumes:
      - ./confluence-5.10.5-source:/usr/src/mymaven
      - ./third-party-libraries:/usr/src/third-party-libraries
      - ./entrypoint.sh:/usr/src/mymaven/entrypoint.sh
    working_dir: /usr/src/mymaven
    command: ./entrypoint.sh